namespace ServerManagerTool.Enums
{
    public enum ServerProfileCategory
    {
        Unknown,
        Administration,
        AutomaticManagement,
        DiscordBot,
        ServerDetails,
        Rules,
        ChatAndNotifications,
        HudAndVisuals,
        Players,
        Dinos,
        Environment,
        Structures,
        Engrams,
        ServerFiles,
        CustomGameUserSettings,
        CustomGameSettings,
        CustomEngineSettings,
        CustomLevels,
        MapSpawnerOverrides,
        CraftingOverrides,
        SupplyCrateOverrides,
        ExcludeItemIndicesOverrides,
        StackSizeOverrides,
        PreventTransferOverrides,
        PGM,
        SOTF,
    }
}
